// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHXe32fK-qGre8GtpAFGkY4TjEuCs2yEg',
    appId: '1:83643204851:web:3faf0a0592141bf8d46386',
    messagingSenderId: '83643204851',
    projectId: 'resta-pucem',
    authDomain: 'resta-pucem.firebaseapp.com',
    databaseURL: 'https://resta-pucem-default-rtdb.firebaseio.com',
    storageBucket: 'resta-pucem.appspot.com',
    measurementId: 'G-YF1CVXVKYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpOFS3EAmBzXuUWhESQhtfdRZ4zAax6q0',
    appId: '1:83643204851:android:7e1ae527fd180bded46386',
    messagingSenderId: '83643204851',
    projectId: 'resta-pucem',
    databaseURL: 'https://resta-pucem-default-rtdb.firebaseio.com',
    storageBucket: 'resta-pucem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs9Pd-OFaBR2-3JZlN49w0jzRvg52EkYU',
    appId: '1:83643204851:ios:1e9974af371a1407d46386',
    messagingSenderId: '83643204851',
    projectId: 'resta-pucem',
    databaseURL: 'https://resta-pucem-default-rtdb.firebaseio.com',
    storageBucket: 'resta-pucem.appspot.com',
    iosClientId: '83643204851-9mt1916sfa7cgqfght4bgpadf7t82ja6.apps.googleusercontent.com',
    iosBundleId: 'com.devel.pucem.hdtFlutter',
  );
}
